# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a7896db65355c0535d80a2f47c2f5f16548e02243301919037f63d7b78901cc74bbe478dfa56fe4f6b68253ae7e982086e683d22bd7aed4bf130e63dcb4416

test:
  secret_key_base: 10532a8cff9a61717e6436e65ddbac391a3e225dcd4470e3c409466bdc301720b44b24e92ac5b39514de7dbfca2d2362bbc6d413ce8ede6eb7edb387948e7ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
